package Server.Domain.UserManager;

public enum Permissions {
    REGISTER,
    OPEN_STORE,
    ADD_PRODUCT_TO_STORE,
    REMOVE_PRODUCT_FROM_STORE,
    UPDATE_PRODUCT_PRICE,
    APPOINT_OWNER,
    APPOINT_MANAGER,
    RECEIVE_STORE_ROLES_INFO
}
